### `rescue`

Starts an exception section of code in a `begin` block. See [exception handling](https://docs.ruby-lang.org/en/3.3/syntax/exceptions_rdoc.html)
